// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMr2eXy3bGI52fZE6ppLDRTu7D4PdXcA4',
    appId: '1:545470530426:web:241e08efad9b96bb158cc3',
    messagingSenderId: '545470530426',
    projectId: 'aqar-hub',
    authDomain: 'aqar-hub.firebaseapp.com',
    storageBucket: 'aqar-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMo91fXAYgU56z_IzNJz9NverqxsB0ntU',
    appId: '1:545470530426:android:9f1f7bdedf3dee92158cc3',
    messagingSenderId: '545470530426',
    projectId: 'aqar-hub',
    storageBucket: 'aqar-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFuAIkXZnAN6UDAUIS21nDft0QyF-TFIA',
    appId: '1:545470530426:ios:17c54ed96f6cc3c0158cc3',
    messagingSenderId: '545470530426',
    projectId: 'aqar-hub',
    storageBucket: 'aqar-hub.firebasestorage.app',
    iosClientId: '545470530426-n0e0rr2f79s6r7ftv9oevhqq21a04su7.apps.googleusercontent.com',
    iosBundleId: 'com.aqarhub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFuAIkXZnAN6UDAUIS21nDft0QyF-TFIA',
    appId: '1:545470530426:ios:17c54ed96f6cc3c0158cc3',
    messagingSenderId: '545470530426',
    projectId: 'aqar-hub',
    storageBucket: 'aqar-hub.firebasestorage.app',
    iosClientId: '545470530426-n0e0rr2f79s6r7ftv9oevhqq21a04su7.apps.googleusercontent.com',
    iosBundleId: 'com.aqarhub.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDp5hXPBA6PGE4CNhCTDwAKJXH2jbSZt8',
    appId: '1:545470530426:web:9e4c5fc593356c20158cc3',
    messagingSenderId: '545470530426',
    projectId: 'aqar-hub',
    authDomain: 'aqar-hub.firebaseapp.com',
    storageBucket: 'aqar-hub.firebasestorage.app',
  );
}